server {
    listen 80;
    server_name _;

    location /static {
        proxy_pass http://backend:5001;
    }

    location /admin {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        resolver 127.0.0.11 valid=30s;
        proxy_pass         http://admin:9999;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    location / {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        proxy_pass         http://backend:5001;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }
}